/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Database {
  constructor(name: string)
  static load(path: string): Database
  save(path: string): void
  listTables(): Array<string>
  createIndex(tableName: string, columnName: string): void
  createUniqueIndex(tableName: string, columnName: string): void
  getTableMetadata(name: string): TableMetadata | null
  insertBatchI64(tableName: string, values: BigInt64Array, numColumns: number): void
  createTable(name: string, columns: Array<ColumnDefinition>): void
  insertRowI64(tableName: string, values: Array<number>): void
  getColumnI64(tableName: string, columnName: string): BigInt64Array
  updateRowI64(tableName: string, id: number, values: Array<number>): void
  deleteRow(tableName: string, id: number): void
  findByI64(tableName: string, columnName: string, value: number): BigInt64Array
  hashJoinI64(table1: string, col1: string, table2: string, col2: string): BigInt64Array
  executeSql(sql: string): any
  prepare(sql: string): PreparedStatement
  queryI64(sql: string): BigInt64Array
  queryJoinI64(sql: string): BigInt64Array
}

export declare class PreparedStatement {
  run(params: Array<number>): void
  allI64(params: Array<number>): BigInt64Array
  runBatch(batchParams: Array<Array<number>>): void
  runBatchI64(flatParams: BigInt64Array, paramsPerRow: number): void
}

export interface ColumnDefinition {
  name: string
  dataType: string
  nullable: boolean
}

export declare const enum DataType {
  Integer = 0,
  Float = 1,
  String = 2,
  Boolean = 3,
  Blob = 4
}

export interface TableMetadata {
  name: string
  rowCount: number
  columnCount: number
}
