/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Cursor {
  next(): any | null
}

export declare class Database {
  constructor(name: string)
  createTable(name: string, columns: Array<ColumnDefinition>): boolean
  insertBatchI64(tableName: string, values: BigInt64Array, numColumns: number): boolean
  insertRowI64(tableName: string, values: Array<number>): boolean
  insertRowString(tableName: string, values: Array<string>): boolean
  insertRowBool(tableName: string, values: Array<boolean>): boolean
  insertRowFloat(tableName: string, values: Array<number>): boolean
  insertRow(tableName: string, values: Array<any | undefined | null>): boolean
  insertOrReplace(tableName: string, values: Array<any | undefined | null>, uniqueColumn: string): boolean
  insertBatchString(tableName: string, values: Array<string>, numColumns: number): boolean
  insertBatchBool(tableName: string, values: Array<boolean>, numColumns: number): boolean
  insertBatchFloat(tableName: string, values: Array<number>, numColumns: number): boolean
  insertBatch(tableName: string, values: Array<any | undefined | null>, numColumns: number): boolean
  updateRowI64(tableName: string, id: number, values: Array<number>): boolean
  updateRowString(tableName: string, id: number, values: Array<string>): boolean
  updateRowBool(tableName: string, id: number, values: Array<boolean>): boolean
  updateRowFloat(tableName: string, id: number, values: Array<number>): boolean
  updateRow(tableName: string, id: number, values: Array<any | undefined | null>): boolean
  updateColumnI64(tableName: string, id: number, columnName: string, value: number): boolean
  updateColumnString(tableName: string, id: number, columnName: string, value: string): boolean
  updateColumnBool(tableName: string, id: number, columnName: string, value: boolean): boolean
  updateColumnFloat(tableName: string, id: number, columnName: string, value: number): boolean
  updateBatchI64(tableName: string, columnName: string, values: BigInt64Array): boolean
  deleteRow(tableName: string, id: number): boolean
  deleteByColumnI64(tableName: string, columnName: string, value: number): number
  deleteByColumnString(tableName: string, columnName: string, value: string): number
  deleteByColumnBool(tableName: string, columnName: string, value: boolean): number
  deleteBatchI64(tableName: string, ids: BigInt64Array): number
  getColumnI64(tableName: string, columnName: string): BigInt64Array
  findByI64(tableName: string, columnName: string, value: number): BigInt64Array
  findByString(tableName: string, columnName: string, value: string): BigInt64Array
  findByBool(tableName: string, columnName: string, value: boolean): BigInt64Array
  getColumnString(tableName: string, columnName: string): Array<string>
  getColumnBool(tableName: string, columnName: string): Array<boolean>
  getColumnFloat(tableName: string, columnName: string): Array<number>
  hashJoinI64(table1: string, col1: string, table2: string, col2: string): BigInt64Array
  getRows(tableName: string, limit?: number | undefined | null, offset?: number | undefined | null): any
  getRowById(tableName: string, id: number): any | null
  getRowByColumnI64(tableName: string, columnName: string, value: number): any | null
  getRowByColumnString(tableName: string, columnName: string, value: string): any | null
  getRowByColumnBool(tableName: string, columnName: string, value: boolean): any | null
  getRowsAsync(tableName: string, limit?: number | undefined | null, offset?: number | undefined | null): Promise<any>
  cursor(tableName: string, batchSize?: number | undefined | null): Cursor
  countRows(tableName: string): number
  sumColumn(tableName: string, columnName: string): number
  minColumn(tableName: string, columnName: string): number
  maxColumn(tableName: string, columnName: string): number
  avgColumn(tableName: string, columnName: string): number
  get schema(): Schema
  beginTransaction(): Transaction
  executeSql(sql: string): any
  prepare(sql: string): PreparedStatement
  queryI64(sql: string): BigInt64Array
  queryJoinI64(sql: string): BigInt64Array
  static load(path: string): Database
  save(path: string): boolean
  listTables(): Array<string>
  createIndex(tableName: string, columnName: string): boolean
  createUniqueIndex(tableName: string, columnName: string): boolean
  createCompositeIndex(tableName: string, columnNames: Array<string>): boolean
  getTableMetadata(name: string): TableMetadata | null
}

export declare class DbError {
  get code(): string
  get message(): string
}

export declare class DynamicSchema {
  constructor()
  register(schemaName: string, fields: Array<SchemaField>): void
  /** Uses streaming parser — validates during JSON tokenization, no intermediate Value tree. */
  parse(schemaName: string, buffer: Buffer): Array<any>
  /** Same as parse() but from JSON string. */
  parseString(schemaName: string, input: string): Array<any>
  /** Parse single record using streaming parser. */
  parseOne(schemaName: string, buffer: Buffer): any
  /**
   * Validate a JS Object by accessing properties directly via napi — no Value intermediate.
   * Returns the object (no conversion overhead).
   * Missing optional fields remain absent (not injected as null).
   * I64 validation uses f64 — values beyond 2^53 may lose precision.
   */
  validateObject(schemaName: string, obj: object): object
  /**
   * Convert a validated serde_json::Value (must be an object) to a Vec<Option<serde_json::Value>>
   * following the schema field order, suitable for database insertion.
   */
  toRowValues(schemaName: string, value: any): Array<any | undefined | null>
  /** Validate a pre-parsed serde_json::Value. Fast path: returns original Value when valid. */
  validate(schemaName: string, value: any): any
}

export declare class PreparedStatement {
  run(params: Array<number>): boolean
  allI64(params: Array<number>): BigInt64Array
  runBatch(batchParams: Array<Array<number>>): boolean
  runBatchValues(flatParams: Array<any | undefined | null>, paramsPerRow: number): boolean
  runBatchI64(flatParams: BigInt64Array, paramsPerRow: number): boolean
}

export declare class Schema {
  /**
   * Returns a description of schema violations in the given row values.
   * Returns an empty array if the row is valid.
   */
  validateRow(tableName: string, values: Array<any>): Array<string>
  getColumnNames(tableName: string): Array<string>
  getColumnType(tableName: string, columnName: string): DataType
  hasColumn(tableName: string, columnName: string): boolean
}

export declare class Transaction {
  commit(): boolean
  rollback(): boolean
}

export interface ColumnDefinition {
  name: string
  dataType: DataType
  /** Defaults to true if not specified */
  nullable?: boolean
}

export declare const enum DataType {
  Integer = 0,
  Float = 1,
  String = 2,
  Boolean = 3,
  Blob = 4
}

export declare const enum FieldType {
  String = 'string',
  I64 = 'i64',
  F64 = 'f64',
  Bool = 'bool',
  Json = 'json',
  ArrayString = 'array:string',
  ArrayI64 = 'array:i64',
  ArrayF64 = 'array:f64'
}

export interface SchemaField {
  name: string
  type: FieldType
  optional?: boolean
}

export interface TableMetadata {
  name: string
  rowCount: number
  columnCount: number
}
