/* auto-generated by NAPI-RS */
/* eslint-disable */

export type TypedArray = Int8Array | Uint8Array | Uint8ClampedArray | Int16Array | Uint16Array | Int32Array | Uint32Array | Float32Array | Float64Array | BigInt64Array | BigUint64Array
export declare class Cursor {
  next(): any | null
}

export declare class Database {
  constructor(name: string)
  createTableFromSchema(tableName: string, dynamicSchema: DynamicSchema, schemaName: string): boolean
  createTable(name: string, columns: Array<ColumnDefinition>): boolean
  insertBatchI64(tableName: string, values: BigInt64Array, numColumns: number): boolean
  insertRowI64(tableName: string, values: Array<number>): boolean
  insertRowString(tableName: string, values: Array<string>): boolean
  insertRowBool(tableName: string, values: Array<boolean>): boolean
  insertRowFloat(tableName: string, values: Array<number>): boolean
  insertObject(tableName: string, obj: object, dynamicSchema: DynamicSchema, schemaName: string): boolean
  insertRow(tableName: string, values: Array<any | undefined | null>): boolean
  insertOrReplace(tableName: string, values: Array<any | undefined | null>, uniqueColumn: string): boolean
  insertBatchString(tableName: string, values: Array<string>, numColumns: number): boolean
  insertBatchBool(tableName: string, values: Array<boolean>, numColumns: number): boolean
  insertBatchFloat(tableName: string, values: Array<number>, numColumns: number): boolean
  insertBatchObjects(tableName: string, objects: unknown[], dynamicSchema: DynamicSchema, schemaName: string): boolean
  insertBatch(tableName: string, values: Array<any | undefined | null>, numColumns: number): boolean
  insertBatchColumnar(tableName: string, columns: object): boolean
  updateRowI64(tableName: string, id: number, values: Array<number>): boolean
  updateRowString(tableName: string, id: number, values: Array<string>): boolean
  updateRowBool(tableName: string, id: number, values: Array<boolean>): boolean
  updateRowFloat(tableName: string, id: number, values: Array<number>): boolean
  updateObject(tableName: string, id: number, obj: object, dynamicSchema: DynamicSchema, schemaName: string): boolean
  updateRow(tableName: string, id: number, values: Array<any | undefined | null>): boolean
  updateColumnI64(tableName: string, id: number, columnName: string, value: number): boolean
  updateColumnString(tableName: string, id: number, columnName: string, value: string): boolean
  updateColumnBool(tableName: string, id: number, columnName: string, value: boolean): boolean
  updateColumnFloat(tableName: string, id: number, columnName: string, value: number): boolean
  updateBatchI64(tableName: string, columnName: string, values: BigInt64Array): boolean
  deleteRow(tableName: string, id: number): boolean
  deleteByColumnI64(tableName: string, columnName: string, value: number): number
  deleteByColumnString(tableName: string, columnName: string, value: string): number
  deleteByColumnBool(tableName: string, columnName: string, value: boolean): number
  deleteBatchI64(tableName: string, ids: BigInt64Array): number
  getColumnI64(tableName: string, columnName: string): BigInt64Array
  findByI64(tableName: string, columnName: string, value: number): BigInt64Array
  findByString(tableName: string, columnName: string, value: string): BigInt64Array
  findByBool(tableName: string, columnName: string, value: boolean): BigInt64Array
  getColumnString(tableName: string, columnName: string): Array<string>
  getColumnBool(tableName: string, columnName: string): Array<boolean>
  getColumnFloat(tableName: string, columnName: string): Array<number>
  hashJoinI64(table1: string, col1: string, table2: string, col2: string): BigInt64Array
  getRows(tableName: string, limit?: number | undefined | null, offset?: number | undefined | null): any
  getRowById(tableName: string, id: number): any | null
  getRowByColumnI64(tableName: string, columnName: string, value: number): any | null
  getRowByColumnString(tableName: string, columnName: string, value: string): any | null
  getRowByColumnBool(tableName: string, columnName: string, value: boolean): any | null
  getRowsAsync(tableName: string, limit?: number | undefined | null, offset?: number | undefined | null): Promise<any>
  cursor(tableName: string, batchSize?: number | undefined | null): Cursor
  countRows(tableName: string): number
  sumColumn(tableName: string, columnName: string): number
  minColumn(tableName: string, columnName: string): number
  maxColumn(tableName: string, columnName: string): number
  avgColumn(tableName: string, columnName: string): number
  get schema(): Schema
  beginTransaction(): Transaction
  executeSql(sql: string): any
  query(sql: string, params?: Array<any | undefined | null> | undefined | null): PreparedStatement
  prepare(sql: string, params?: Array<any | undefined | null> | undefined | null): PreparedStatement
  queryI64(sql: string): BigInt64Array
  queryJoinI64(sql: string): BigInt64Array
  exportTableToArrowIpc(tableName: string): Buffer
  /**
   * Convert an array of JS objects to Arrow IPC buffer using the table's schema.
   * Each object's properties are mapped to columns by name, with correct Arrow types.
   * The returned buffer can be passed directly to insertFromArrow / updateFromArrow.
   */
  objectsToArrowIpc(tableName: string, objects: Array<any>): Buffer
  importTableFromArrowIpc(tableName: string, buffer: Buffer): boolean
  /**
   * Create a table from an Arrow IPC buffer's schema (zero-copy schema definition).
   * The IPC buffer must contain at least a valid Arrow schema header (data is optional).
   * Returns the number of columns created.
   */
  createTableFromArrowIpc(tableName: string, buffer: Buffer): number
  static load(path: string): Database
  save(path: string): boolean
  listTables(): Array<string>
  createIndex(tableName: string, columnName: string): boolean
  createUniqueIndex(tableName: string, columnName: string): boolean
  createCompositeIndex(tableName: string, columnNames: Array<string>): boolean
  getTableMetadata(name: string): TableMetadata | null
  createQueryBuilder(): JsQueryBuilder
}

export declare class DbError {
  get code(): string
  get message(): string
}

export declare class DynamicSchema {
  constructor()
  register(schemaName: string, fields: Array<SchemaField>): void
  /** Uses streaming parser — validates during JSON tokenization. */
  parse(schemaName: string, buffer: Buffer): Array<any>
  /** Same as parse() but from JSON string. Uses streaming parser. */
  parseString(schemaName: string, input: string): Array<any>
  /** Parse single record and validate against schema. Uses streaming parser. */
  parseOne(schemaName: string, buffer: Buffer): any
  /**
   * Validate a JS Object by accessing properties directly via napi — no Value intermediate.
   * Returns the object (no conversion overhead).
   * Missing optional fields remain absent (not injected as null).
   */
  validateObject(schemaName: string, obj: object): object
  /**
   * Convert a validated Object to a Vec<Option<serde_json::Value>>
   * following the schema field order, suitable for database insertion.
   */
  toRowValues(schemaName: string, obj: object): Array<any | undefined | null>
  /**
   * Convert a registered schema to an Arrow IPC buffer compatible with createTableFromArrowIpc.
   * The buffer contains the Arrow schema (no data rows) that createTableFromArrowIpc can read
   * to define a table with matching columns.
   */
  toArrowIpc(schemaName: string): Buffer
  /** Validate a pre-parsed serde_json::Value. Fast path: returns original Value when valid. */
  validate(schemaName: string, value: any): any
}

export declare class JsQueryBuilder {
  select(table: string): this
  insert(table: string): this
  update(table: string): this
  delete(table: string): this
  columns(cols: Array<string>): this
  set(column: string, value: any): this
  whereEq(column: string, value: any): this
  whereNeq(column: string, value: any): this
  whereGt(column: string, value: any): this
  whereGte(column: string, value: any): this
  whereLt(column: string, value: any): this
  whereLte(column: string, value: any): this
  whereLike(column: string, pattern: string): this
  orderBy(column: string, descending: boolean): this
  limit(limit: number): this
  offset(offset: number): this
  /** INNER JOIN: ON this_column = other_table.other_column */
  join(otherTable: string, thisColumn: string, otherColumn: string): this
  execute(): any
  first(): any | null
  /**
   * Execute query and return data column-oriented: { colName: [values...] }
   * Avoids per-row JSON object overhead. Uses a direct table read for simple
   * SELECT * (no filters, no joins, no order) — bypasses Row cloning entirely.
   */
  executeColumnar(): any
  /**
   * Execute query and return results as Apache Arrow IPC buffer.
   * Avoids JSON serialization — the JS side can parse with @apache-arrow.
   * Uses a direct table read for simple SELECT * (no filters, no joins).
   */
  executeArrow(): Buffer
  /**
   * Batch insert — flat row-major values. Much faster than per-row insert loops.
   * `values` is a flat array: [row1col1, row1col2, row2col1, row2col2, ...]
   */
  insertBatch(table: string, values: Array<any>, numColumns: number): number
  /**
   * Batch insert from interleaved i64 arrays.
   * BigInt64Array interleaved: [row1col1, row1col2, row2col1, row2col2, ...]
   */
  insertBatchI64(table: string, values: BigInt64Array, numColumns: number): number
  /** Batch insert from interleaved f64 arrays. */
  insertBatchF64(table: string, values: Float64Array, numColumns: number): number
  /**
   * Insert from Arrow IPC buffer — zero-copy, no JSON serialization.
   * Parses the RecordBatch and inserts all rows into the table.
   */
  insertFromArrow(table: string, buffer: Buffer): number
  /**
   * Update rows from Arrow IPC buffer — zero-copy, no JSON serialization.
   * The Arrow data must include an "id" column to identify rows.
   * Other columns in the Arrow buffer overwrite the corresponding table columns.
   * Returns the number of rows updated.
   */
  updateFromArrow(table: string, buffer: Buffer): number
  /**
   * Insert columnar — takes { colName: TypedArray | Array, ... }.
   * Avoids both serde_json (for typed arrays) and Arrow IPC serialization.
   * Column names are read from the table schema (order determined by schema).
   */
  insertColumnar(table: string, columns: object): number
  /**
   * Update columnar — takes { id: TypedArray, colName: TypedArray | Array, ... }.
   * Requires an "id" column to identify rows. All other columns are merged
   * into the existing row data (column by column).
   * Avoids both serde_json (for typed arrays) and Arrow IPC serialization.
   */
  updateColumnar(table: string, columns: object): number
  /** Batch insert from string arrays. */
  insertBatchString(table: string, values: Array<string>, numColumns: number): number
  /**
   * Insert multiple rows from an array of JS objects.
   * Uses the table schema to determine column order and types.
   * Avoids manual columnar construction — schema-aware batch insert.
   */
  insertFromObjects(table: string, objects: Array<any>): number
  /**
   * Update multiple rows from an array of JS objects.
   * Each object must include an "id" property to identify the row.
   * Other properties are merged into the existing row data.
   * Uses the table schema for column name resolution.
   */
  updateFromObjects(table: string, objects: Array<any>): number
}

export declare class PreparedStatement {
  run(params?: Array<number> | undefined | null): boolean
  allI64(params?: Array<number> | undefined | null): BigInt64Array
  runBatch(batchParams: Array<Array<number>>): boolean
  runBatchValues(flatParams: Array<any | undefined | null>, paramsPerRow: number): boolean
  runBatchI64(flatParams: BigInt64Array, paramsPerRow: number): boolean
  runBatchString(flatParams: Array<string>, paramsPerRow: number): boolean
  runBatchBool(flatParams: Array<boolean>, paramsPerRow: number): boolean
  all(params?: Array<any | undefined | null> | undefined | null): any
  get(params?: Array<any | undefined | null> | undefined | null): any | null
}

export declare class Schema {
  /**
   * Returns a description of schema violations in the given row values.
   * Returns an empty array if the row is valid.
   */
  validateRow(tableName: string, values: Array<any>): Array<string>
  getColumnNames(tableName: string): Array<string>
  getColumnType(tableName: string, columnName: string): DataType
  hasColumn(tableName: string, columnName: string): boolean
}

export declare class Transaction {
  commit(): boolean
  rollback(): boolean
}

export interface ColumnDefinition {
  name: string
  dataType: DataType
  /** Defaults to true if not specified */
  nullable?: boolean
}

export declare const enum DataType {
  Integer = 0,
  Float = 1,
  String = 2,
  Boolean = 3,
  Blob = 4,
  Json = 5,
  ArrayString = 6,
  ArrayI64 = 7,
  ArrayF64 = 8
}

export interface SchemaField {
  name: string
  type: DataType
  optional?: boolean
}

export interface TableMetadata {
  name: string
  rowCount: number
  columnCount: number
}
